# name: Build & Release next
# 
# on:
#   push:
#     branches:
#       - main
#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:
# 
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           ref: 'main'
# 
#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'
# 
#       - name: Install dependencies
#         run: npm install
# 
#       - name: Build the library
#         run: npm run build
# 
#   release:
#     runs-on: ubuntu-latest
#     needs: [build]
#     steps:
#     - uses: actions/checkout@master
#     - name: Create release
#       uses: Roang-zero1/github-create-release-action@v2
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     - name: Upload release artifacts
#       uses: Roang-zero1/github-upload-release-artifacts-action@v2
#       with:
#         args: "dist/*"
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
