name: Deploy Storybook to GitHub Pages

on:
  push:
    # tags:
    #   - "v[0-1].*"
    branches:
      - next
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build

      - name: DEBUG
        run: pwd && ls -al

      - name: DEBUG
        run: git remote -v

      - name: 'Fetch master branch and checkout/copy over only the docs folder to gh-pages'
        run: |
          git clone -b next https://github.com/epfl-si/epfl-elements-react.git next
          cd next
          npm install
          npm run build
          npx storybook build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
