name: Deploy Storybook to GitHub Pages

on:
  push:
    # tags:
    #   - "v[0-1].*"
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout the 'next' branch
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Get the version in package.json
        run: |
          EER_VERSION=$(cat package.json | grep version | cut -d'"' -f4)
          echo "EER_VERSION=${EER_VERSION}" >> $GITHUB_ENV

      - name: Install npm dependencies
        run: npm install

      - name: Build Storybook
        run: npx storybook build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static

  library:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout the 'next' branch
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Install npm dependencies
        run: npm install

      - name: debug version
        run: echo "Version is ${{ env.EER_VERSION }} XXX"

      - name: Build the epfl-elements-react library
        run: npm run build

      - name: Create the package.json
        run: jq -n --arg version v0.0.1 '{"name":"epfl-elements-react","version":$version,"description":"EPFL Elements React Library","main":"index.js","repository":"github:epfl-si/epfl-elements-react","keywords":["epfl-elements-react"],"author":"EPFL ISAS-FSD","license":"MIT","types":"./index.d.ts","bugs":{"url":"https://github.com/epfl-si/epfl-elements-react/issues"},"homepage":"https://github.com/epfl-si/epfl-elements-react#readme"}' > dist/package.json

      - name: Create the epfl-elements-react package
        run: |
          npm pack ./dist/
          cp epfl-elements-react-*.tgz epfl-elements-react.tgz

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: epfl-elements-react
          path: |
            epfl-elements-react.tgz

  # release:
